apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
data:
  db_host: "postgres-service"
  db_port: "5432"
  db_name: "chatbot_db"
  redis_host: "redis-service"
  redis_port: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secrets
type: Opaque
data:
  # Note: These are placeholder values - in a real environment, replace with actual base64-encoded secrets
  db_user: cG9zdGdyZXM=  # "postgres" encoded
  db_password: cG9zdGdyZXNwYXNzd29yZA==  # "postgrespassword" encoded
  jwt_secret: c3VwZXJzZWNyZXRrZXlmb3Jqd3RhdXRoZW50aWNhdGlvbg==  # example secret
  openai_api_key: eW91cl9vcGVuYWlfa2V5  # replace in actual deployment
  elevenlabs_api_key: eW91cl9lbGV2ZW5sYWJzX2tleQ==  # replace in actual deployment
